apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: fsx-snapshot-class
driver: fsx.openzfs.csi.aws.com
deletionPolicy: Delete
parameters:
  Tags: '[{"Key": "OPENZFS", "Value": "OPENZFS"}]'
